[package]
name = "surrealdb_json_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.81"
clap = { version = "4.5.3", features = ["derive"] }
once_cell = "1.19.0"
serde = "1.0.197"
serde_json = "1.0.114"
surrealdb = { version = "1.3.1", features = ["kv-mem"] }
tokio = { version = "1.36.0", features = ["full"] }
